[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

[[patches]]
[patches.pattern]
target = "card_character.lua"
pattern = 'self.children.card.states.visible = false'
position = "before"
payload = "self.children.card:set_seal('Red')"
match_indent = true

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = 'Jimbo:say_stuff(5)'
position = "after"
payload = """
G.E_MANAGER:add_event(Event({
    trigger = 'after',
    delay = 1,
    blocking = false,
    func = (function()
        if G.OVERLAY_MENU and G.OVERLAY_MENU:get_UIE_by_ID('jimbo_spot') then 
            Jimbo.ui_object_updated = true
            Jimbo:add_speech_bubble('again', nil, {quip = true})
            Jimbo:say_stuff(2)
        end
        return true
    end)
}))
G.E_MANAGER:add_event(Event({
    trigger = 'after',
    delay = 1.5,
    blocking = false,
    func = (function()
        if G.OVERLAY_MENU and G.OVERLAY_MENU:get_UIE_by_ID('jimbo_spot') then 
            Jimbo.ui_object_updated = true
            Jimbo:add_speech_bubble('lq_'..math.random(1,10), nil, {quip = true})
            Jimbo:say_stuff(5)
        end
        return true
    end)
}))
"""
match_indent = true

[[patches]]
[patches.pattern]
target = "state_events.lua"
pattern = 'Jimbo:say_stuff(5)'
position = "after"
payload = """
G.E_MANAGER:add_event(Event({
    trigger = 'after',
    delay = 1,
    blocking = false,
    func = (function()
        if G.OVERLAY_MENU and G.OVERLAY_MENU:get_UIE_by_ID('jimbo_spot') then 
            Jimbo.ui_object_updated = true
            Jimbo:add_speech_bubble('again', nil, {quip = true})
            Jimbo:say_stuff(2)
        end
        return true
    end)
}))
G.E_MANAGER:add_event(Event({
    trigger = 'after',
    delay = 1.5,
    blocking = false,
    func = (function()
        if G.OVERLAY_MENU and G.OVERLAY_MENU:get_UIE_by_ID('jimbo_spot') then 
            Jimbo.ui_object_updated = true
            Jimbo:add_speech_bubble('wq_'..math.random(1,10), nil, {quip = true})
            Jimbo:say_stuff(5)
        end
        return true
    end)
}))
"""
match_indent = true